/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SwellPointRouteImport } from './routes/swell-point'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as KleinRouteImport } from './routes/klein'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as K10USRouteImport } from './routes/K10US'
import { Route as IndexRouteImport } from './routes/index'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SwellPointRoute = SwellPointRouteImport.update({
  id: '/swell-point',
  path: '/swell-point',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const KleinRoute = KleinRouteImport.update({
  id: '/klein',
  path: '/klein',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const K10USRoute = K10USRouteImport.update({
  id: '/K10US',
  path: '/K10US',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/K10US': typeof K10USRoute
  '/admin': typeof AdminRoute
  '/coming-soon': typeof ComingSoonRoute
  '/klein': typeof KleinRoute
  '/merch': typeof MerchRoute
  '/offers': typeof OffersRoute
  '/swell-point': typeof SwellPointRoute
  '/thank-you': typeof ThankYouRoute
  '/unlock': typeof UnlockRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/K10US': typeof K10USRoute
  '/admin': typeof AdminRoute
  '/coming-soon': typeof ComingSoonRoute
  '/klein': typeof KleinRoute
  '/merch': typeof MerchRoute
  '/offers': typeof OffersRoute
  '/swell-point': typeof SwellPointRoute
  '/thank-you': typeof ThankYouRoute
  '/unlock': typeof UnlockRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/K10US': typeof K10USRoute
  '/admin': typeof AdminRoute
  '/coming-soon': typeof ComingSoonRoute
  '/klein': typeof KleinRoute
  '/merch': typeof MerchRoute
  '/offers': typeof OffersRoute
  '/swell-point': typeof SwellPointRoute
  '/thank-you': typeof ThankYouRoute
  '/unlock': typeof UnlockRoute
  '/vip': typeof VipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/K10US'
    | '/admin'
    | '/coming-soon'
    | '/klein'
    | '/merch'
    | '/offers'
    | '/swell-point'
    | '/thank-you'
    | '/unlock'
    | '/vip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/K10US'
    | '/admin'
    | '/coming-soon'
    | '/klein'
    | '/merch'
    | '/offers'
    | '/swell-point'
    | '/thank-you'
    | '/unlock'
    | '/vip'
  id:
    | '__root__'
    | '/'
    | '/K10US'
    | '/admin'
    | '/coming-soon'
    | '/klein'
    | '/merch'
    | '/offers'
    | '/swell-point'
    | '/thank-you'
    | '/unlock'
    | '/vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  K10USRoute: typeof K10USRoute
  AdminRoute: typeof AdminRoute
  ComingSoonRoute: typeof ComingSoonRoute
  KleinRoute: typeof KleinRoute
  MerchRoute: typeof MerchRoute
  OffersRoute: typeof OffersRoute
  SwellPointRoute: typeof SwellPointRoute
  ThankYouRoute: typeof ThankYouRoute
  UnlockRoute: typeof UnlockRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swell-point': {
      id: '/swell-point'
      path: '/swell-point'
      fullPath: '/swell-point'
      preLoaderRoute: typeof SwellPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klein': {
      id: '/klein'
      path: '/klein'
      fullPath: '/klein'
      preLoaderRoute: typeof KleinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/K10US': {
      id: '/K10US'
      path: '/K10US'
      fullPath: '/K10US'
      preLoaderRoute: typeof K10USRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  K10USRoute: K10USRoute,
  AdminRoute: AdminRoute,
  ComingSoonRoute: ComingSoonRoute,
  KleinRoute: KleinRoute,
  MerchRoute: MerchRoute,
  OffersRoute: OffersRoute,
  SwellPointRoute: SwellPointRoute,
  ThankYouRoute: ThankYouRoute,
  UnlockRoute: UnlockRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
